name: ui_challenge
description: UI challenge
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.6 <4.0.0"

dependencies:
  animate_do: ^3.0.2
  dotted_border: ^2.1.0
  carousel_slider: ^4.2.1
  cached_network_image: ^3.2.3
  staggered_grid_view_flutter: ^0.0.4

  firebase_auth: ^4.7.3
  firebase_core: ^2.15.1
  cloud_firestore: ^4.9.0
  firebase_storage: ^11.2.6
  firebase_analytics: ^10.5.1

  flutter:
    sdk: flutter
  flutter_local_notifications: ^15.1.0+1
  flutter_localizations:
    sdk: flutter

  lottie: ^2.6.0
  iconsax: ^0.0.8
  awesome_icons: ^1.1.0
  cupertino_icons: ^1.0.2

  image_picker: ^1.0.2
  image_cropper: ^5.0.0

  provider: ^6.0.5
  google_sign_in: ^6.1.4
  connectivity_plus: ^5.0.0
  shared_preferences: ^2.2.0
  permission_handler: ^11.0.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/
    - assets/onboard/
    - assets/animation/
